# Generated by Django 2.1.1 on 2018-10-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_holder', '0003_auto_20181008_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
